version: '3.12'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:8000" 
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - HOST_IP=${HOST_IP}
      - HOST_PORT=${HOST_PORT}
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 